DefaultContentLanguage = 'ko'
baseURL = "https://0makes0.com/"
#languageCode = "en-us"
title = "Zero Makes Zero"
summaryLength = "10"
googleAnalytics = "UA-180203838-1"

hasCJKLanguage = true
staticDir = 'static'

disablePathToLower = true

[params]
  archive = "archive"
  next = "Next"
  previous = "Previous"
  photo = "Photo"
  video = "Video"
  description = "Description"

[languages]
  [languages.ko]
  baseURL = 'https://0makes0.com/'
  languageName = "한글"
  weight = 1
  [languages.ko.params]
    archive = "아카이브"
    next = "다음"
    previous = "이전"
    photo = "사진"
    video = "영상"
    description = "프로그램 설명"

  [languages.en]
  baseURL = 'https://0makes0.com/en'
  languageName = "English"
  weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
